### ISSUE TITLE
Add categories and sentiment to sequence labels

### ISSUE THREAD

**Issue by apmoore1** [apmoore1/target-extraction#3]
Within target_extraction.data_types.TargetText.sequence_labels it would be good to have two flags e.g. categories, sentiments where if True then the sequence labels will be like so:
B-POS or
B-LAPTOP#GENERAL

This would roughly follow the same type of structure as the AllenNLP [SpanBasedF1Measure](https://github.com/allenai/allennlp/blob/master/allennlp/training/metrics/span_based_f1_measure.py#L23-L271)

**Comment by lacls** [comment]
Thank you a bunch for your public code.
I am looking forward to seeing your new improvement.
